### PR TITLE
#158574893 Show details of rides user has taken.

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
Modify myrides.html to show details of rides taken

**Description of Task to be completed?**
- Have myrides.html listing details of rides given

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-details-of-rides-taken-158574893
- Open `myrides.html` using your favorite browser.

**What are the relevant pivotal tracker stories?**
[#158574893](https://www.pivotaltracker.com/story/show/158574893)

**Screenshots**
details of rides taken

### CODE REVIEW

**Comment by artorious** [comment]
Looks good. I especially like a that it captures all the  important details of a ride taken in the past

**Comment by TheSteelGuy** [comment]
Nice one bro , look intuitive, i cant find any issue

**Comment by LWanjiru** [comment]
Please fix this conflicts @meshack-mbuvi

**Comment by meshack-mbuvi** [comment]
@LWanjiru conflicts have been resolved here

**Review by LWanjiru — APPROVED** [review]
Looks good.

**Pull request merged**
