### PR TITLE
#158434528 add interface for drivers to create new ride offer

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
This pull request creates new_ride.html with a form for creating new ride offer

**Description of Task to be completed?**
At minimum, the new_ride.html page should have the following:
- form with input fields for drivers to enter ride details.
- button for drivers to submit/save ride offer details
- Navigation links to other pages.

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-create-ride-158434528`
-  Open new_ride.html using your favorite browser.

**What are the relevant pivotal tracker stories?**
[[#158434528]](https://www.pivotaltracker.com/story/show/158434528)

**Screenshot**
new_ride

### CODE REVIEW

**Comment by Ogollah** [comment]
Have you restricted the routes traveled? I think if it not regional it should be left open to writing any route one desires.

**Comment by TheSteelGuy** [comment]
Good one though next dont use the term functionality, these are just interfaces

**Comment by meshack-mbuvi** [comment]
Updated the design

**Comment by LWanjiru** [comment]
Looks good.

**Pull request merged**
