### PR TITLE
#158425280 Modify driver.html to show  number of rides given

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
Modify driver.html to show number of rides given

**Description of Task to be completed?**
- Have driver.html showing number of rides given
- Add link for creating new ride offer and another one for showing details of the rides given

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-number-of-rides-given-158425280
- Open `driver.html` using your favorite browser.

**What are the relevant pivotal tracker stories?**
[#158425280](https://www.pivotaltracker.com/story/show/158425280)

**Screenshots**
number of ride given

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
what happens if i click the click here for more details?

**Comment by meshack-mbuvi** [comment]
When you click the link, it will show the details of the rides you have offered

**Comment by LWanjiru** [comment]
Please fix these conflicts @meshack-mbuvi

**Comment by meshack-mbuvi** [comment]
@LWanjiru Solved by removing the conflicting file.

**Review by LWanjiru — APPROVED** [review]
Looks good, can be merged

**Pull request merged**
