### PR TITLE
#158423574 Add feature for user to view details of a particular ride offer 

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
This pull request creates ridedetails.html showing details of a particular ride offer.

**Description of Task to be completed?**
At minimum, the ridedetails.html page should have the following:
- Image of the driver's car
- Route of the planned journey
- Costs to be incurred by users in proportion to their covered distance
- Link for user to click if they want to join the ride.
- Capacity of the car

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-view-ride-details-158423574`
-  Open ridedetails.html using your favorite browser.

**What are the relevant pivotal tracker stories?**
[[#158423574]](https://www.pivotaltracker.com/story/show/158423574)

**Screenshot**
ridedetails

### CODE REVIEW

**Comment by boswellgathu** [comment]
For the rating just say Driver rating

**Comment by Ogollah** [comment]
The image is not well presented

**Comment by TheSteelGuy** [comment]
This great meeen, you have really thought it out. @Ogollah i think it is best if you give such a feedback you also suggest a way to do better,

**Comment by meshack-mbuvi** [comment]
@Ogollah  How about it now?

**Comment by LWanjiru** [comment]
Looks good. Can be merged. 

A bit curious though, how does the passenger get in touch with the driver for the meeting up logistics?

**Comment by meshack-mbuvi** [comment]
@LWanjiru I was thinking to have a feature where driver and passenger can send messages to each other through the platform. Not sure whether I will be able to implement it

**Comment by LWanjiru** [comment]
Looks good.

**Pull request merged**
