### PR TITLE
#158423574 Add feature for user to view details of a particula ride offer

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
This pull request creates _ridedetails.html_ showing details of a particular ride offer.

**Description of Task to be completed?**
At minimum, the ridedetails.html page should have the following:
- Image of the driver's car
- Route of the planned journey
- Costs to be incurred by users in proportion to their covered distance
- Link for user to click if they want to join the ride.
- Capacity of the car

**How should this be manually tested?**
- Clone this repository
-  In your terminal, cd ride-my-way
-   `git checkout ft-view-ride-details-158423574`
    Open ridedetails.html using your favorite browser.

**What are the relevant pivotal tracker stories?**
[#158423574] https://www.pivotaltracker.com/story/show/158423574
**Screenshots**
offer details

### CODE REVIEW

**Comment by larryTheGeek** [comment]
good design bro

**Comment by Xerrex** [comment]
I like that your PRs are really detailed.

**Comment by evamaina** [comment]
Nice PR

**Comment by PaulKitonyi** [comment]
Nice and descriptive PR. Consider making your PT ID clickable instead of having the link beside ID.

**Comment by Ogollah** [comment]
This is cool.

**Pull request closed without merging**
