### PR TITLE
#158574983 Add details of rides given by driver

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
Add details of rides given by driver

**Description of Task to be completed?**
- create myoffers.html page
- Add table listing details of rides given by driver to myoffers.html

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-details-of-rides-given-158574983
- Open `myoffers.html` using your favorite browser.

**What are the relevant pivotal tracker stories?**
[#158574983](https://www.pivotaltracker.com/story/show/158574983)

**Screenshots**
details of ride given

### CODE REVIEW

**Comment by MasherJames** [comment]
good arrangement of the ride offers given,,,, the ui is appealing

**Comment by Ogollah** [comment]
looks nice.

**Comment by LWanjiru** [comment]
Please resolve the conflicts @meshack-mbuvi

**Comment by meshack-mbuvi** [comment]
@LWanjiru  Following the method for the on command-line has resulted into the PR being merged, should I reopen it for review?

**Pull request merged**
