### PR TITLE
Build site homepage with css and background image.

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**Role of this pull request**
adds homepage to the web application.

**Description**
The homepage has a navigation bar to guide users on various endpoints offered by the app. It has also a welcome message and links for user sign up in-case user has not created any account user and sign in for user to sign in to their existing accounts.

**Manual test**
- clone this repository and cd into it.
- checkout ft-homepage-158238855
- cd into the UI folder
- open index.html using your favorite browser.

**Relevant pivotal tracker story**
    #158238855].

**screenshot**
home

### CODE REVIEW

**Comment by DerKip** [comment]
It's responsive...good use of media queries. consider adding the app name on the navbar, otherwise, you can proceed merging to develop

**Comment by Derrickkip** [comment]
Looks good :+1:

**Comment by micahoriaso** [comment]
Good clean code. I like your css markup

**Comment by Teddykavooh** [comment]
Nice.Remember to pad your footer from the right.

**Comment by Teddykavooh** [comment]
I'll see what i can do.Thanks alot.

**Pull request merged**
