### PR TITLE
#158435083 Users can see driver rating and reviews

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
Avails driver rating and reviews to users.

**Description of Task to be completed?**
- Add _rating.html_ page with rating and reviews about a given driver.

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-driver-rating-158435083
- Open rating.html using your favorite browser.

**What are the relevant pivotal tracker stories?**
[#158435083](https://www.pivotaltracker.com/story/show/158435083)

**Screenshots**
rating

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
Waah you have really put a lot of effort, good one...

**Comment by artorious** [comment]
Clean, clear, detailed. Awsome

**Review by LWanjiru — APPROVED** [review]
Impressive, I observe you are very detailed in your UI design, I hope you are sharing this knowledge with your peers.

**Comment by meshack-mbuvi** [comment]
I usually share whatever I know

**Pull request merged**
