### PR TITLE
#158423949 Add feature for user to view rides user has requested to join.

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?**
This pull request creates myrequests.html listing all rides user has requested to join.

**Description of Task to be completed?**
At minimum, the myrequests.html page should have the following:
- A table showing a list of rides user has requested to join.
- Each ride should have an associated status showing whether its accepted or reject or pending.
- Also there should be a column to show whether user has taken that ride.

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way
- `git checkout ft-ride-requests-158423949`
- Open user.html using your favorite browser.

**What are the relevant pivotal tracker stories?**
[[#158423949]](https://www.pivotaltracker.com/story/show/158423949)

**Screenshots**
myrequests

### CODE REVIEW

**Comment by Ogollah** [comment]
This looks great I love it.

**Comment by TheSteelGuy** [comment]
Nice UI this is history on rides

**Comment by SelaDanti** [comment]
Very User friendly

**Comment by LWanjiru** [comment]
Curious question, what is the difference between the `status` and `taken` fields in this table? @meshack-mbuvi

**Comment by meshack-mbuvi** [comment]
`status` indicates whether the ride has been accepted, rejected or pending while `taken` indicates whether user has taken that given ride

**Pull request merged**
